---
all:
  vars:
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
    ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
    ansible_port: 2222
  hosts:
    noob:
      ansible_host: 14.225.218.83